### ISSUE TITLE
UndefVarError: bytesize not defined

### ISSUE THREAD

**Issue by shuuul** [sethaxen/MRC.jl#16]
When calling `updateheader!`, it reports `UndefVarError: bytesize not defined`. 
I think this is due to the https://github.com/sethaxen/MRCFile.jl/blob/28aa5ca36f1fd350dff58fe249338e97142c7193/src/data.jl#L93 .

**Comment by sethaxen** [comment]
Ah yes, that should be `sizeof(extendedheader(d)))`. Wasn't caught because we don't have tests for any of the extended header machinery.
